const fs = require('fs');

// Load existing master dict
const master = JSON.parse(fs.readFileSync('scratch/master_comprehensive_dict.json', 'utf8'));

// ─── NEW KEYS for Alerts Page, Social Page, app.js dynamic strings, and location names ───
const newKeys = {
  en: {
    // Alerts page - dynamic strings
    alertsLoadingMsg: "Scanning multi-regional meteorological radars and IMD warning bulletins...",
    alertsRedWarning: "Red Warnings (Take Action)",
    alertsOrangeAlert: "Orange Alerts (Be Prepared)",
    alertsYellowWatch: "Yellow Watches (Be Updated)",
    alertsImpactedStates: "Impacted States / UTs",
    alertsSeverityRed: "RED WARNING",
    alertsSeverityOrange: "ORANGE ALERT",
    alertsSeverityYellow: "YELLOW WATCH",
    alertsValidHorizon: "Valid Horizon",
    alertsPublicAdvisory: "Public Safety Advisory:",
    alertsViewAreaMap: "View Area Map",
    alertsNoActiveTitle: "No Active Alerts in this Category",
    alertsNoActiveDesc: "All monitored meteorological stations for this filter are currently within normal baseline thresholds.",
    alertsNoSubsTitle: "No personal early-warning alerts configured yet.",
    alertsNoSubsDesc: "Configure an alert below to get alerted for high rain, heatwave, or gale winds in your area!",
    alertsMonitoringActive: "Monitoring Active",
    alertsPaused: "Paused",
    alertsTrigger: "Trigger:",
    alertsThreshold: "Threshold:",
    alertsBrowserPush: "Browser Push",
    alertsAudioSiren: "Audio Siren",
    alertsNoGroundReportsTitle: "No Registered Ground Reports Found",
    alertsNoGroundReportsDesc: "Be the first to report local weather incidents, waterlogging, or wind damage!",
    alertsSubmitGroundReport: "Submit Ground Report",
    alertsCategoryHeavyRain: "Heavy Rain",
    alertsCategoryFlood: "Flash Flood",
    alertsCategoryCyclone: "Cyclone",
    alertsCategoryHeatwave: "Heatwave",
    alertsCategoryFog: "Dense Fog",
    alertsCategoryDustStorm: "Dust Storm",
    alertsCategoryStrongWinds: "High Winds",
    alertsCategoryHailstorm: "Hailstorm",
    alertsCategoryThunderstorm: "Thunderstorm",
    alertsCategoryOther: "Severe Weather",
    alertsStatusVerified: "VERIFIED",
    alertsStatusPending: "PENDING",
    alertsStatusFlagged: "FLAGGED",
    alertsSoundEas: "EAS Dual-Tone Siren",
    alertsSoundSiren: "Municipal Alarm",
    alertsSoundPulse: "Pulse Staccato",
    alertsSoundPing: "Radar Ping",
    alertsSoundBell: "Advisory Bell",
    alertsHazardHeavyRain: "Heavy Rainfall / Downpour",
    alertsHazardHeatwave: "Extreme Heatwave",
    alertsHazardThunderstorm: "Severe Thunderstorm / High Wind",
    alertsHazardColdWave: "Severe Cold Wave",
    alertsResumeMonitoring: "Resume monitoring",
    alertsPauseMonitoring: "Pause monitoring",
    alertsTestTone: "Test this alert tone",
    alertsDeleteAlert: "Delete alert",
    alertsImpactLow: "IMD criterion: Moderate (5-15mm/h), Heavy (15-64mm/h), Very Heavy (>64mm/h)",
    alertsImpactHeatwave: "IMD criterion: Heatwave at 40°C in plains, Severe Heatwave at 45°C+",
    alertsImpactThunderstorm: "Squall criterion: Gusts exceeding 45-60 km/h with lightning hazard",
    alertsImpactColdWave: "Cold wave criterion: Plains min temperature drops to 10°C or lower",
    alertsDetectingGps: "Detecting Device GPS...",
    alertsGpsCaptured: "GPS Captured",

    // Social page - dynamic strings
    socialFetchingStream: "Fetching Live Intelligence Stream...",
    socialFetchingDesc: "Ingesting real-time alerts and bulletins from IMD Official, Google News, UN GDACS, X, and Instagram...",
    socialNoPostsTitle: "No Intelligence Posts Found",
    socialNoPostsDesc: "No live signals match the currently selected filter. You can ingest the latest real-time signals or view all platform feeds.",
    socialIngestBtn: "Ingest Live Signals Now",
    socialShowAllBtn: "Show All Platforms",
    socialCatHeavyRain: "Heavy Rain",
    socialCatFlood: "Flood",
    socialCatCyclone: "Cyclone Alert",
    socialCatHeatwave: "Heatwave",
    socialCatHailstorm: "Hailstorm",
    socialCatThunderstorm: "Thunderstorm",
    socialCatOther: "Weather Event",
    socialPlatformImd: "IMD Official Desk",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS Disaster Alert",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "Open on X",
    socialOpenImd: "IMD Advisory",
    socialOpenInstagram: "Open on Instagram",
    socialViewUnAlert: "View UN Alert",
    socialReadArticle: "Read Article",
    socialUrgency: "Urgency:",
    socialViewStation: "View Station",
    socialInferred: "Inferred:",
    socialNational: "National",
    socialViewRadar: "View Radar »",
    socialFetchingSignals: "Fetching Signals...",
    socialFetchLive: "Fetch Live Signals",

    // app.js - forecast table and UI strings
    forecastToday: "Today",
    forecastTodayHourly: "Today (24h) Hourly View",
    forecastDayTable: "-Day Forecast Table View",
    forecastTodayTitle: "Today's 24-Hour Hourly Forecast",
    forecastDayTitle: "-Day Extended Weather Forecast",
    forecastTimeInterval: "TIME INTERVAL (IST)",
    forecastDateDay: "DATE & DAY",
    forecastContextComprehensive: "(Comprehensive)",
    forecastLiveTelemetry: "Live Telemetry • Updated",
    forecastIST: "IST",
    forecastRainChance: "% CHANCE",
    forecastClearSky: "Clear Sky",
    forecastRainShowers: "Rain Showers",
    forecastClearNight: "Clear Night",
    forecastSunnyDay: "Sunny Day",
    forecastPartlyCloudy: "Partly Cloudy",
    forecastNoData: "No forecast data available.",
    forecastUpdated: "Updated",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-day meteorological forecast CSV.",
    forecastDownloadError: "No forecast data available to export.",

    // Location/GPS display strings
    gpsCaptured: "Location detected via GPS!",
    gpsError: "Could not acquire GPS position. Please enter city manually.",
    locationIndia: "India",
    locationGpsCoords: "My Location",
    locationDetected: "Detected Location",
    locationCoordsFmt: "Custom Coordinate",

    // Admin portal texts
    adminLoginBtn: "Admin Login",
    adminPortalBtn: "Admin Portal",

    // Alerts stat summary label
    alertsJustNow: "Just now",
    alertsMinsAgo: "m ago",
    alertsHoursAgo: "h ago",
    alertsDaysAgo: "d ago",
  },

  hi: {
    alertsLoadingMsg: "बहु-क्षेत्रीय मौसम विज्ञान रडार और IMD चेतावनी बुलेटिन स्कैन हो रहे हैं...",
    alertsRedWarning: "लाल चेतावनियाँ (तुरंत कार्रवाई करें)",
    alertsOrangeAlert: "नारंगी अलर्ट (तैयार रहें)",
    alertsYellowWatch: "पीला वॉच (अपडेट रहें)",
    alertsImpactedStates: "प्रभावित राज्य / केंद्र शासित प्रदेश",
    alertsSeverityRed: "लाल चेतावनी",
    alertsSeverityOrange: "नारंगी अलर्ट",
    alertsSeverityYellow: "पीला वॉच",
    alertsValidHorizon: "वैध अवधि",
    alertsPublicAdvisory: "सार्वजनिक सुरक्षा सलाह:",
    alertsViewAreaMap: "क्षेत्र का नक्शा देखें",
    alertsNoActiveTitle: "इस श्रेणी में कोई सक्रिय अलर्ट नहीं",
    alertsNoActiveDesc: "इस फिल्टर के लिए सभी निगरानी मौसम स्टेशन वर्तमान में सामान्य सीमाओं के भीतर हैं।",
    alertsNoSubsTitle: "अभी तक कोई व्यक्तिगत अर्ली-वार्निंग अलर्ट सेट नहीं है।",
    alertsNoSubsDesc: "नीचे एक अलर्ट सेट करें ताकि अत्यधिक बारिश, लू या तेज़ हवाओं के लिए अलर्ट मिल सके!",
    alertsMonitoringActive: "निगरानी सक्रिय",
    alertsPaused: "रोका गया",
    alertsTrigger: "ट्रिगर:",
    alertsThreshold: "सीमा:",
    alertsBrowserPush: "ब्राउज़र पुश",
    alertsAudioSiren: "ऑडियो सायरन",
    alertsNoGroundReportsTitle: "कोई पंजीकृत ग्राउंड रिपोर्ट नहीं मिली",
    alertsNoGroundReportsDesc: "स्थानीय मौसम घटनाओं, जलभराव, या हवा के नुकसान की रिपोर्ट करने वाले पहले बनें!",
    alertsSubmitGroundReport: "ग्राउंड रिपोर्ट सबमिट करें",
    alertsCategoryHeavyRain: "भारी बारिश",
    alertsCategoryFlood: "अचानक बाढ़",
    alertsCategoryCyclone: "चक्रवात",
    alertsCategoryHeatwave: "लू",
    alertsCategoryFog: "घना कोहरा",
    alertsCategoryDustStorm: "धूल भरी आँधी",
    alertsCategoryStrongWinds: "तेज़ हवाएं",
    alertsCategoryHailstorm: "ओलावृष्टि",
    alertsCategoryThunderstorm: "आंधी-तूफ़ान",
    alertsCategoryOther: "गंभीर मौसम",
    alertsStatusVerified: "सत्यापित",
    alertsStatusPending: "लंबित",
    alertsStatusFlagged: "फ्लैग किया गया",
    alertsSoundEas: "EAS दोहरी-टोन सायरन",
    alertsSoundSiren: "नगरपालिका अलार्म",
    alertsSoundPulse: "पल्स स्टेकाटो",
    alertsSoundPing: "रडार पिंग",
    alertsSoundBell: "सलाहकार घंटी",
    alertsHazardHeavyRain: "भारी वर्षा / मूसलाधार बारिश",
    alertsHazardHeatwave: "अत्यधिक लू",
    alertsHazardThunderstorm: "तीव्र आंधी / तेज़ हवा",
    alertsHazardColdWave: "गंभीर शीतलहर",
    alertsResumeMonitoring: "निगरानी फिर शुरू करें",
    alertsPauseMonitoring: "निगरानी रोकें",
    alertsTestTone: "इस अलर्ट टोन का परीक्षण करें",
    alertsDeleteAlert: "अलर्ट हटाएं",
    alertsImpactLow: "IMD मानदंड: मध्यम (5-15mm/h), भारी (15-64mm/h), अत्यधिक भारी (>64mm/h)",
    alertsImpactHeatwave: "IMD मानदंड: मैदानों में 40°C पर लू, 45°C+ पर गंभीर लू",
    alertsImpactThunderstorm: "स्क्वॉल मानदंड: बिजली के साथ 45-60 km/h से अधिक झोंके",
    alertsImpactColdWave: "शीतलहर मानदंड: मैदानों में न्यूनतम तापमान 10°C या उससे नीचे",
    alertsDetectingGps: "डिवाइस GPS खोजा जा रहा है...",
    alertsGpsCaptured: "GPS कैप्चर हो गया",
    socialFetchingStream: "लाइव इंटेलिजेंस स्ट्रीम लाई जा रही है...",
    socialFetchingDesc: "IMD आधिकारिक, Google News, UN GDACS, X और Instagram से रियल-टाइम अलर्ट और बुलेटिन इनजेस्ट हो रहे हैं...",
    socialNoPostsTitle: "कोई इंटेलिजेंस पोस्ट नहीं मिला",
    socialNoPostsDesc: "वर्तमान में चुने गए फ़िल्टर से कोई लाइव सिग्नल मेल नहीं खाता। आप नवीनतम रियल-टाइम सिग्नल इनजेस्ट कर सकते हैं या सभी प्लेटफार्म फीड देख सकते हैं।",
    socialIngestBtn: "अभी लाइव सिग्नल इनजेस्ट करें",
    socialShowAllBtn: "सभी प्लेटफार्म दिखाएं",
    socialCatHeavyRain: "भारी बारिश",
    socialCatFlood: "बाढ़",
    socialCatCyclone: "चक्रवात अलर्ट",
    socialCatHeatwave: "लू",
    socialCatHailstorm: "ओलावृष्टि",
    socialCatThunderstorm: "आंधी-तूफ़ान",
    socialCatOther: "मौसम घटना",
    socialPlatformImd: "IMD आधिकारिक डेस्क",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS आपदा अलर्ट",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "X पर खोलें",
    socialOpenImd: "IMD सलाह",
    socialOpenInstagram: "Instagram पर खोलें",
    socialViewUnAlert: "UN अलर्ट देखें",
    socialReadArticle: "लेख पढ़ें",
    socialUrgency: "तात्कालिकता:",
    socialViewStation: "स्टेशन देखें",
    socialInferred: "अनुमानित:",
    socialNational: "राष्ट्रीय",
    socialViewRadar: "राडार देखें »",
    socialFetchingSignals: "सिग्नल ला रहे हैं...",
    socialFetchLive: "लाइव सिग्नल लाएं",
    forecastToday: "आज",
    forecastTodayHourly: "आज (24 घंटे) प्रति घंटे दृश्य",
    forecastDayTable: "-दिन पूर्वानुमान तालिका",
    forecastTodayTitle: "आज का 24-घंटे का प्रति घंटा पूर्वानुमान",
    forecastDayTitle: "-दिन विस्तृत मौसम पूर्वानुमान",
    forecastTimeInterval: "समय अंतराल (IST)",
    forecastDateDay: "दिनांक और दिन",
    forecastContextComprehensive: "(समग्र)",
    forecastLiveTelemetry: "लाइव टेलीमेट्री • अपडेट किया",
    forecastIST: "IST",
    forecastRainChance: "% संभावना",
    forecastClearSky: "साफ आसमान",
    forecastRainShowers: "बारिश की बौछार",
    forecastClearNight: "साफ रात",
    forecastSunnyDay: "धूप वाला दिन",
    forecastPartlyCloudy: "आंशिक रूप से बादल",
    forecastNoData: "कोई पूर्वानुमान डेटा उपलब्ध नहीं।",
    forecastUpdated: "अपडेट किया",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-दिन का मौसम पूर्वानुमान CSV।",
    forecastDownloadError: "निर्यात के लिए कोई पूर्वानुमान डेटा उपलब्ध नहीं।",
    gpsCaptured: "GPS द्वारा स्थान पता चला!",
    gpsError: "GPS स्थान प्राप्त नहीं हो सका। कृपया शहर मैन्युअल रूप से दर्ज करें।",
    locationIndia: "भारत",
    locationGpsCoords: "मेरा स्थान",
    locationDetected: "पता लगाया गया स्थान",
    locationCoordsFmt: "कस्टम निर्देशांक",
    adminLoginBtn: "व्यवस्थापक लॉगिन",
    adminPortalBtn: "व्यवस्थापक पोर्टल",
    alertsJustNow: "अभी",
    alertsMinsAgo: "मि॰ पहले",
    alertsHoursAgo: "घं॰ पहले",
    alertsDaysAgo: "दिन पहले",
  },

  mr: {
    alertsLoadingMsg: "बहु-क्षेत्रीय हवामान रडार आणि IMD चेतावणी बुलेटिन स्कॅन होत आहेत...",
    alertsRedWarning: "लाल इशारे (त्वरित कृती करा)",
    alertsOrangeAlert: "नारिंगी सतर्कता (तयार राहा)",
    alertsYellowWatch: "पिवळी नजर (अपडेट राहा)",
    alertsImpactedStates: "प्रभावित राज्ये / केंद्रशासित प्रदेश",
    alertsSeverityRed: "लाल इशारा",
    alertsSeverityOrange: "नारिंगी सतर्कता",
    alertsSeverityYellow: "पिवळी नजर",
    alertsValidHorizon: "वैध कालावधी",
    alertsPublicAdvisory: "सार्वजनिक सुरक्षा सल्ला:",
    alertsViewAreaMap: "क्षेत्राचा नकाशा पहा",
    alertsNoActiveTitle: "या श्रेणीत कोणतेही सक्रिय सतर्कता नाही",
    alertsNoActiveDesc: "या फिल्टरसाठी सर्व निरीक्षण हवामान केंद्रे सध्या सामान्य बेसलाइन मर्यादेत आहेत.",
    alertsNoSubsTitle: "अजून कोणताही वैयक्तिक अर्ली-वार्निंग अलर्ट सेट केलेला नाही.",
    alertsNoSubsDesc: "जास्त पाऊस, उष्माघात किंवा वादळी वाऱ्यांसाठी अलर्ट मिळण्यासाठी खाली एक अलर्ट सेट करा!",
    alertsMonitoringActive: "देखरेख सक्रिय",
    alertsPaused: "थांबवले",
    alertsTrigger: "ट्रिगर:",
    alertsThreshold: "उंबरठा:",
    alertsBrowserPush: "ब्राउझर पुश",
    alertsAudioSiren: "ऑडिओ सायरन",
    alertsNoGroundReportsTitle: "कोणते नोंदणीकृत ग्राउंड अहवाल सापडले नाहीत",
    alertsNoGroundReportsDesc: "स्थानिक हवामान घटना, जलभराव किंवा वाऱ्याच्या नुकसानाची तक्रार करणारे पहिले व्हा!",
    alertsSubmitGroundReport: "ग्राउंड अहवाल सबमिट करा",
    alertsCategoryHeavyRain: "जड पाऊस",
    alertsCategoryFlood: "अचानक पूर",
    alertsCategoryCyclone: "चक्रीवादळ",
    alertsCategoryHeatwave: "उष्माघात",
    alertsCategoryFog: "दाट धुके",
    alertsCategoryDustStorm: "धुळीचे वादळ",
    alertsCategoryStrongWinds: "जोरदार वारे",
    alertsCategoryHailstorm: "गारपीट",
    alertsCategoryThunderstorm: "वादळ-पाऊस",
    alertsCategoryOther: "गंभीर हवामान",
    alertsStatusVerified: "सत्यापित",
    alertsStatusPending: "प्रलंबित",
    alertsStatusFlagged: "फ्लॅग केलेले",
    alertsSoundEas: "EAS दुहेरी-टोन सायरन",
    alertsSoundSiren: "महापालिका अलार्म",
    alertsSoundPulse: "पल्स स्टेकाटो",
    alertsSoundPing: "राडार पिंग",
    alertsSoundBell: "सल्लागार घंटी",
    alertsHazardHeavyRain: "मुसळधार पाऊस",
    alertsHazardHeatwave: "अत्यधिक उष्माघात",
    alertsHazardThunderstorm: "तीव्र वादळ / जोरदार वारे",
    alertsHazardColdWave: "गंभीर थंडीची लाट",
    alertsResumeMonitoring: "देखरेख पुन्हा सुरू करा",
    alertsPauseMonitoring: "देखरेख थांबवा",
    alertsTestTone: "हा अलर्ट टोन तपासा",
    alertsDeleteAlert: "अलर्ट हटवा",
    alertsImpactLow: "IMD निकष: मध्यम (5-15mm/h), जड (15-64mm/h), अत्यधिक जड (>64mm/h)",
    alertsImpactHeatwave: "IMD निकष: मैदानात 40°C वर उष्माघात, 45°C+ वर गंभीर उष्माघात",
    alertsImpactThunderstorm: "स्क्वॉल निकष: विजांसह 45-60 km/h पेक्षा जास्त झोके",
    alertsImpactColdWave: "थंडीची लाट निकष: मैदानात किमान तापमान 10°C किंवा खाली",
    alertsDetectingGps: "डिव्हाइस GPS शोधत आहे...",
    alertsGpsCaptured: "GPS कॅप्चर झाले",
    socialFetchingStream: "लाइव्ह इंटेलिजेन्स स्ट्रीम आणत आहे...",
    socialFetchingDesc: "IMD आधिकारिक, Google News, UN GDACS, X आणि Instagram वरून रिअल-टाइम अलर्ट इनजेस्ट होत आहेत...",
    socialNoPostsTitle: "कोणतेही इंटेलिजेन्स पोस्ट सापडले नाहीत",
    socialNoPostsDesc: "सध्या निवडलेल्या फिल्टरशी कोणतेही लाइव्ह सिग्नल जुळत नाहीत.",
    socialIngestBtn: "आत्ता लाइव्ह सिग्नल इनजेस्ट करा",
    socialShowAllBtn: "सर्व प्लॅटफॉर्म दाखवा",
    socialCatHeavyRain: "जड पाऊस",
    socialCatFlood: "पूर",
    socialCatCyclone: "चक्रीवादळ सतर्कता",
    socialCatHeatwave: "उष्माघात",
    socialCatHailstorm: "गारपीट",
    socialCatThunderstorm: "वादळ-पाऊस",
    socialCatOther: "हवामान घटना",
    socialPlatformImd: "IMD अधिकृत डेस्क",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS आपत्ती सतर्कता",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "X वर उघडा",
    socialOpenImd: "IMD सल्ला",
    socialOpenInstagram: "Instagram वर उघडा",
    socialViewUnAlert: "UN सतर्कता पहा",
    socialReadArticle: "लेख वाचा",
    socialUrgency: "तातडी:",
    socialViewStation: "स्टेशन पहा",
    socialInferred: "अनुमानित:",
    socialNational: "राष्ट्रीय",
    socialViewRadar: "राडार पहा »",
    socialFetchingSignals: "सिग्नल आणत आहे...",
    socialFetchLive: "लाइव्ह सिग्नल आणा",
    forecastToday: "आज",
    forecastTodayHourly: "आज (24 तास) प्रति तास दृश्य",
    forecastDayTable: "-दिवस अंदाज तक्ता",
    forecastTodayTitle: "आजचा 24-तासांचा प्रति तास अंदाज",
    forecastDayTitle: "-दिवस विस्तारित हवामान अंदाज",
    forecastTimeInterval: "वेळ मध्यांतर (IST)",
    forecastDateDay: "दिनांक आणि दिवस",
    forecastContextComprehensive: "(सर्वसमावेशक)",
    forecastLiveTelemetry: "लाइव्ह टेलिमेट्री • अपडेट केले",
    forecastIST: "IST",
    forecastRainChance: "% शक्यता",
    forecastClearSky: "स्वच्छ आकाश",
    forecastRainShowers: "पावसाच्या सरी",
    forecastClearNight: "स्वच्छ रात्र",
    forecastSunnyDay: "सनी दिवस",
    forecastPartlyCloudy: "अंशतः ढगाळ",
    forecastNoData: "कोणताही अंदाज डेटा उपलब्ध नाही.",
    forecastUpdated: "अपडेट केले",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-दिवस मौसम अंदाज CSV.",
    forecastDownloadError: "निर्यात करण्यासाठी कोणताही अंदाज डेटा उपलब्ध नाही.",
    gpsCaptured: "GPS द्वारे स्थान शोधले!",
    gpsError: "GPS स्थान मिळू शकले नाही. कृपया शहर मॅन्युअली प्रविष्ट करा.",
    locationIndia: "भारत",
    locationGpsCoords: "माझे स्थान",
    locationDetected: "शोधलेले स्थान",
    locationCoordsFmt: "कस्टम निर्देशांक",
    adminLoginBtn: "प्रशासक लॉगिन",
    adminPortalBtn: "प्रशासक पोर्टल",
    alertsJustNow: "आत्ताच",
    alertsMinsAgo: "मि॰ पूर्वी",
    alertsHoursAgo: "ता॰ पूर्वी",
    alertsDaysAgo: "दिवसांपूर्वी",
  },

  bn: {
    alertsLoadingMsg: "বহু-আঞ্চলিক আবহাওয়া রাডার ও IMD সতর্কতা বুলেটিন স্ক্যান হচ্ছে...",
    alertsRedWarning: "লাল সতর্কতা (তাৎক্ষণিক পদক্ষেপ নিন)",
    alertsOrangeAlert: "কমলা সতর্কতা (প্রস্তুত থাকুন)",
    alertsYellowWatch: "হলুদ পর্যবেক্ষণ (আপডেট থাকুন)",
    alertsImpactedStates: "প্রভাবিত রাজ্য / কেন্দ্রশাসিত অঞ্চল",
    alertsSeverityRed: "লাল সতর্কতা",
    alertsSeverityOrange: "কমলা সতর্কতা",
    alertsSeverityYellow: "হলুদ পর্যবেক্ষণ",
    alertsValidHorizon: "বৈধ সময়কাল",
    alertsPublicAdvisory: "জনসাধারণের নিরাপত্তা পরামর্শ:",
    alertsViewAreaMap: "এলাকার মানচিত্র দেখুন",
    alertsNoActiveTitle: "এই বিভাগে কোনো সক্রিয় সতর্কতা নেই",
    alertsNoActiveDesc: "এই ফিল্টারের জন্য পর্যবেক্ষিত সকল আবহাওয়া কেন্দ্র বর্তমানে স্বাভাবিক সীমার মধ্যে।",
    alertsNoSubsTitle: "এখনো কোনো ব্যক্তিগত আর্লি-ওয়ার্নিং অ্যালার্ট সেট করা হয়নি।",
    alertsNoSubsDesc: "ভারী বৃষ্টি, তাপপ্রবাহ বা ঝড়ো হাওয়ার জন্য অ্যালার্ট পেতে নিচে একটি অ্যালার্ট সেট করুন!",
    alertsMonitoringActive: "পর্যবেক্ষণ সক্রিয়",
    alertsPaused: "বিরতিতে",
    alertsTrigger: "ট্রিগার:",
    alertsThreshold: "সীমা:",
    alertsBrowserPush: "ব্রাউজার পুশ",
    alertsAudioSiren: "অডিও সাইরেন",
    alertsNoGroundReportsTitle: "কোনো নিবন্ধিত গ্রাউন্ড রিপোর্ট পাওয়া যায়নি",
    alertsNoGroundReportsDesc: "স্থানীয় আবহাওয়া ঘটনা, জলাবদ্ধতা বা ক্ষতির রিপোর্ট করুন!",
    alertsSubmitGroundReport: "গ্রাউন্ড রিপোর্ট জমা দিন",
    alertsCategoryHeavyRain: "ভারী বৃষ্টি",
    alertsCategoryFlood: "হঠাৎ বন্যা",
    alertsCategoryCyclone: "ঘূর্ণিঝড়",
    alertsCategoryHeatwave: "তাপপ্রবাহ",
    alertsCategoryFog: "ঘন কুয়াশা",
    alertsCategoryDustStorm: "বালুঝড়",
    alertsCategoryStrongWinds: "প্রবল বাতাস",
    alertsCategoryHailstorm: "শিলাবৃষ্টি",
    alertsCategoryThunderstorm: "বজ্রঝড়",
    alertsCategoryOther: "তীব্র আবহাওয়া",
    alertsStatusVerified: "যাচাইকৃত",
    alertsStatusPending: "অপেক্ষমাণ",
    alertsStatusFlagged: "চিহ্নিত",
    alertsSoundEas: "EAS দ্বৈত-টোন সাইরেন",
    alertsSoundSiren: "পৌরসভা অ্যালার্ম",
    alertsSoundPulse: "পালস স্তাকাতো",
    alertsSoundPing: "রাডার পিং",
    alertsSoundBell: "পরামর্শ ঘণ্টা",
    alertsHazardHeavyRain: "ভারী বৃষ্টিপাত / মুষলধার বৃষ্টি",
    alertsHazardHeatwave: "চরম তাপপ্রবাহ",
    alertsHazardThunderstorm: "তীব্র ঝড় / প্রবল বাতাস",
    alertsHazardColdWave: "তীব্র শীতলঢেউ",
    alertsResumeMonitoring: "পর্যবেক্ষণ পুনরায় শুরু করুন",
    alertsPauseMonitoring: "পর্যবেক্ষণ বিরতি দিন",
    alertsTestTone: "এই অ্যালার্ট টোন পরীক্ষা করুন",
    alertsDeleteAlert: "অ্যালার্ট মুছুন",
    alertsImpactLow: "IMD মানদণ্ড: মাঝারি (5-15mm/h), ভারী (15-64mm/h), অতি ভারী (>64mm/h)",
    alertsImpactHeatwave: "IMD মানদণ্ড: সমতলে 40°C-এ তাপপ্রবাহ, 45°C+-এ তীব্র তাপপ্রবাহ",
    alertsImpactThunderstorm: "স্কোয়াল মানদণ্ড: বজ্রপাত সহ 45-60 km/h-এর বেশি ঝোড়ো হাওয়া",
    alertsImpactColdWave: "শীতলঢেউ মানদণ্ড: সমতলে সর্বনিম্ন তাপমাত্রা 10°C বা নিচে",
    alertsDetectingGps: "ডিভাইস GPS খোঁজা হচ্ছে...",
    alertsGpsCaptured: "GPS ধরা হয়েছে",
    socialFetchingStream: "লাইভ ইন্টেলিজেন্স স্ট্রিম আনা হচ্ছে...",
    socialFetchingDesc: "IMD অফিসিয়াল, Google News, UN GDACS, X এবং Instagram থেকে রিয়েল-টাইম অ্যালার্ট ইনজেস্ট হচ্ছে...",
    socialNoPostsTitle: "কোনো ইন্টেলিজেন্স পোস্ট পাওয়া যায়নি",
    socialNoPostsDesc: "নির্বাচিত ফিল্টারের সাথে কোনো লাইভ সিগন্যাল মেলে না।",
    socialIngestBtn: "এখনই লাইভ সিগন্যাল ইনজেস্ট করুন",
    socialShowAllBtn: "সব প্ল্যাটফর্ম দেখান",
    socialCatHeavyRain: "ভারী বৃষ্টি",
    socialCatFlood: "বন্যা",
    socialCatCyclone: "ঘূর্ণিঝড় সতর্কতা",
    socialCatHeatwave: "তাপপ্রবাহ",
    socialCatHailstorm: "শিলাবৃষ্টি",
    socialCatThunderstorm: "বজ্রঝড়",
    socialCatOther: "আবহাওয়া ঘটনা",
    socialPlatformImd: "IMD অফিসিয়াল ডেস্ক",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS দুর্যোগ সতর্কতা",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "X-এ খুলুন",
    socialOpenImd: "IMD পরামর্শ",
    socialOpenInstagram: "Instagram-এ খুলুন",
    socialViewUnAlert: "UN সতর্কতা দেখুন",
    socialReadArticle: "নিবন্ধ পড়ুন",
    socialUrgency: "জরুরিতা:",
    socialViewStation: "স্টেশন দেখুন",
    socialInferred: "অনুমানিত:",
    socialNational: "জাতীয়",
    socialViewRadar: "রাডার দেখুন »",
    socialFetchingSignals: "সিগন্যাল আনা হচ্ছে...",
    socialFetchLive: "লাইভ সিগন্যাল আনুন",
    forecastToday: "আজ",
    forecastTodayHourly: "আজ (24 ঘণ্টা) প্রতি ঘণ্টা দৃশ্য",
    forecastDayTable: "-দিনের পূর্বাভাস তালিকা",
    forecastTodayTitle: "আজকের 24-ঘণ্টার প্রতি ঘণ্টা পূর্বাভাস",
    forecastDayTitle: "-দিনের বিস্তারিত আবহাওয়া পূর্বাভাস",
    forecastTimeInterval: "সময় বিরতি (IST)",
    forecastDateDay: "তারিখ ও দিন",
    forecastContextComprehensive: "(ব্যাপক)",
    forecastLiveTelemetry: "লাইভ টেলিমেট্রি • আপডেট করা হয়েছে",
    forecastIST: "IST",
    forecastRainChance: "% সম্ভাবনা",
    forecastClearSky: "পরিষ্কার আকাশ",
    forecastRainShowers: "বৃষ্টির ঝাপটা",
    forecastClearNight: "পরিষ্কার রাত",
    forecastSunnyDay: "রোদেলা দিন",
    forecastPartlyCloudy: "আংশিক মেঘলা",
    forecastNoData: "কোনো পূর্বাভাস ডেটা পাওয়া যায়নি।",
    forecastUpdated: "আপডেট করা হয়েছে",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-দিনের আবহাওয়া পূর্বাভাস CSV।",
    forecastDownloadError: "রপ্তানির জন্য কোনো পূর্বাভাস ডেটা নেই।",
    gpsCaptured: "GPS-এর মাধ্যমে অবস্থান পাওয়া গেছে!",
    gpsError: "GPS অবস্থান পাওয়া যায়নি। অনুগ্রহ করে শহর ম্যানুয়ালি লিখুন।",
    locationIndia: "ভারত",
    locationGpsCoords: "আমার অবস্থান",
    locationDetected: "শনাক্ত করা অবস্থান",
    locationCoordsFmt: "কাস্টম স্থানাঙ্ক",
    adminLoginBtn: "অ্যাডমিন লগইন",
    adminPortalBtn: "অ্যাডমিন পোর্টাল",
    alertsJustNow: "এইমাত্র",
    alertsMinsAgo: "মি আগে",
    alertsHoursAgo: "ঘ আগে",
    alertsDaysAgo: "দিন আগে",
  },

  ta: {
    alertsLoadingMsg: "பல மண்டல வானிலை ரேடார்கள் மற்றும் IMD எச்சரிக்கை அறிவிப்புகள் ஸ்கேன் ஆகின்றன...",
    alertsRedWarning: "சிவப்பு எச்சரிக்கைகள் (உடனடி நடவடிக்கை எடுங்கள்)",
    alertsOrangeAlert: "ஆரஞ்சு விழிப்புணர்வு (தயாராக இருங்கள்)",
    alertsYellowWatch: "மஞ்சள் கண்காணிப்பு (புதுப்பிக்கப்படுங்கள்)",
    alertsImpactedStates: "பாதிக்கப்பட்ட மாநிலங்கள் / யூ.டி",
    alertsSeverityRed: "சிவப்பு எச்சரிக்கை",
    alertsSeverityOrange: "ஆரஞ்சு விழிப்புணர்வு",
    alertsSeverityYellow: "மஞ்சள் கண்காணிப்பு",
    alertsValidHorizon: "செல்லுபடியாகும் காலம்",
    alertsPublicAdvisory: "பொது பாதுகாப்பு ஆலோசனை:",
    alertsViewAreaMap: "பகுதி வரைபடம் பார்க்கவும்",
    alertsNoActiveTitle: "இந்த வகையில் செயலில் உள்ள விழிப்பு இல்லை",
    alertsNoActiveDesc: "இந்த வடிகட்டிக்கான அனைத்து கண்காணிக்கப்பட்ட வானிலை நிலையங்களும் தற்போது இயல்பான வரம்பிற்குள் உள்ளன.",
    alertsNoSubsTitle: "இன்னும் எந்த தனிப்பட்ட அர்லி-வார்னிங் விழிப்பும் அமைக்கப்படவில்லை.",
    alertsNoSubsDesc: "கனமழை, வெப்பலை அல்லது புயல் காற்றுக்கு விழிப்பு பெற கீழே விழிப்பு அமைக்கவும்!",
    alertsMonitoringActive: "கண்காணிப்பு செயலில்",
    alertsPaused: "இடைநிறுத்தப்பட்டது",
    alertsTrigger: "தூண்டுதல்:",
    alertsThreshold: "வரம்பு:",
    alertsBrowserPush: "உலாவி புஷ்",
    alertsAudioSiren: "ஆடியோ சைரன்",
    alertsNoGroundReportsTitle: "பதிவுசெய்யப்பட்ட தரை அறிக்கைகள் எதுவும் கிடைக்கவில்லை",
    alertsNoGroundReportsDesc: "உள்ளூர் வானிலை சம்பவங்களை, நீர்தேக்கம் அல்லது காற்று சேதத்தை முதலில் புகாரளிக்கவும்!",
    alertsSubmitGroundReport: "தரை அறிக்கை சமர்ப்பிக்கவும்",
    alertsCategoryHeavyRain: "கனமழை",
    alertsCategoryFlood: "திடீர் வெள்ளம்",
    alertsCategoryCyclone: "சுழல்காற்று",
    alertsCategoryHeatwave: "வெப்பலை",
    alertsCategoryFog: "அடர்ந்த பனிமூட்டம்",
    alertsCategoryDustStorm: "மண்புயல்",
    alertsCategoryStrongWinds: "வலிய காற்று",
    alertsCategoryHailstorm: "ஆலங்கட்டி மழை",
    alertsCategoryThunderstorm: "இடிமழை",
    alertsCategoryOther: "கடும் வானிலை",
    alertsStatusVerified: "சரிபார்க்கப்பட்டது",
    alertsStatusPending: "நிலுவையில்",
    alertsStatusFlagged: "கொடியிடப்பட்டது",
    alertsSoundEas: "EAS இரட்டை-டோன் சைரன்",
    alertsSoundSiren: "நகராட்சி அலாரம்",
    alertsSoundPulse: "பல்ஸ் ஸ்டக்காட்டோ",
    alertsSoundPing: "ரேடார் பிங்",
    alertsSoundBell: "ஆலோசனை மணி",
    alertsHazardHeavyRain: "கனமழை / கொட்டும் மழை",
    alertsHazardHeatwave: "தீவிர வெப்பலை",
    alertsHazardThunderstorm: "தீவிர புயல் / வலிய காற்று",
    alertsHazardColdWave: "தீவிர குளிர்அலை",
    alertsResumeMonitoring: "கண்காணிப்பை மீண்டும் தொடங்கவும்",
    alertsPauseMonitoring: "கண்காணிப்பை இடைநிறுத்தவும்",
    alertsTestTone: "இந்த விழிப்பு தொனியை சோதிக்கவும்",
    alertsDeleteAlert: "விழிப்பை நீக்கவும்",
    alertsImpactLow: "IMD அளவுகோல்: மிதமான (5-15mm/h), கனமான (15-64mm/h), மிக கனமான (>64mm/h)",
    alertsImpactHeatwave: "IMD அளவுகோல்: சமவெளியில் 40°C-ல் வெப்பலை, 45°C+-ல் தீவிர வெப்பலை",
    alertsImpactThunderstorm: "ஸ்குவால் அளவுகோல்: இடியுடன் 45-60 km/h-க்கு அதிகமான காற்று",
    alertsImpactColdWave: "குளிர்அலை அளவுகோல்: சமவெளியில் குறைந்தபட்ச வெப்பநிலை 10°C அல்லது கீழே",
    alertsDetectingGps: "சாதன GPS கண்டறியப்படுகிறது...",
    alertsGpsCaptured: "GPS பதிவு செய்யப்பட்டது",
    socialFetchingStream: "நேரடி இன்டெலிஜென்ஸ் ஸ்ட்ரீம் கொண்டுவரப்படுகிறது...",
    socialFetchingDesc: "IMD அதிகாரப்பூர்வம், Google News, UN GDACS, X மற்றும் Instagram இலிருந்து நிகழ்நேர எச்சரிக்கைகள் சேர்க்கப்படுகின்றன...",
    socialNoPostsTitle: "இன்டெலிஜென்ஸ் பதிவுகள் எதுவும் கிடைக்கவில்லை",
    socialNoPostsDesc: "தேர்ந்தெடுத்த வடிகட்டியுடன் நேரடி சிக்னல்கள் எதுவும் பொருந்தவில்லை.",
    socialIngestBtn: "இப்போதே நேரடி சிக்னல்களை சேர்க்கவும்",
    socialShowAllBtn: "அனைத்து தளங்களையும் காட்டவும்",
    socialCatHeavyRain: "கனமழை",
    socialCatFlood: "வெள்ளம்",
    socialCatCyclone: "சுழல்காற்று விழிப்பு",
    socialCatHeatwave: "வெப்பலை",
    socialCatHailstorm: "ஆலங்கட்டி மழை",
    socialCatThunderstorm: "இடிமழை",
    socialCatOther: "வானிலை நிகழ்வு",
    socialPlatformImd: "IMD அதிகாரப்பூர்வ டெஸ்க்",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS பேரிடர் விழிப்பு",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "X-ல் திறக்கவும்",
    socialOpenImd: "IMD ஆலோசனை",
    socialOpenInstagram: "Instagram-ல் திறக்கவும்",
    socialViewUnAlert: "UN விழிப்பைப் பாருங்கள்",
    socialReadArticle: "கட்டுரை படிக்கவும்",
    socialUrgency: "அவசரம்:",
    socialViewStation: "நிலையம் பார்க்கவும்",
    socialInferred: "அனுமானிக்கப்பட்டது:",
    socialNational: "தேசிய",
    socialViewRadar: "ரேடார் பாருங்கள் »",
    socialFetchingSignals: "சிக்னல்கள் கொண்டுவரப்படுகின்றன...",
    socialFetchLive: "நேரடி சிக்னல்களை கொண்டுவாருங்கள்",
    forecastToday: "இன்று",
    forecastTodayHourly: "இன்று (24 மணி) மணிக்கு மணி காட்சி",
    forecastDayTable: "-நாள் முன்னறிவிப்பு அட்டவணை",
    forecastTodayTitle: "இன்றைய 24 மணி நேர மணிவாரியான முன்னறிவிப்பு",
    forecastDayTitle: "-நாள் விரிவான வானிலை முன்னறிவிப்பு",
    forecastTimeInterval: "நேர இடைவெளி (IST)",
    forecastDateDay: "தேதி மற்றும் நாள்",
    forecastContextComprehensive: "(விரிவான)",
    forecastLiveTelemetry: "நேரடி டெலிமெட்ரி • புதுப்பிக்கப்பட்டது",
    forecastIST: "IST",
    forecastRainChance: "% வாய்ப்பு",
    forecastClearSky: "தெளிவான வானம்",
    forecastRainShowers: "மழைச்சாரல்",
    forecastClearNight: "தெளிவான இரவு",
    forecastSunnyDay: "வெயில் நாள்",
    forecastPartlyCloudy: "பகுதி மேகமூட்டம்",
    forecastNoData: "முன்னறிவிப்பு தரவு இல்லை.",
    forecastUpdated: "புதுப்பிக்கப்பட்டது",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-நாள் வானிலை முன்னறிவிப்பு CSV.",
    forecastDownloadError: "ஏற்றுமதிக்கு முன்னறிவிப்பு தரவு இல்லை.",
    gpsCaptured: "GPS மூலம் இடம் கண்டறியப்பட்டது!",
    gpsError: "GPS இடம் கிடைக்கவில்லை. நகரத்தை கைமுறையாக உள்ளிடவும்.",
    locationIndia: "இந்தியா",
    locationGpsCoords: "என் இடம்",
    locationDetected: "கண்டறியப்பட்ட இடம்",
    locationCoordsFmt: "தனிப்பயன் ஆயத்தொகுப்பு",
    adminLoginBtn: "நிர்வாக உள்நுழைவு",
    adminPortalBtn: "நிர்வாக போர்டல்",
    alertsJustNow: "இப்போதுதான்",
    alertsMinsAgo: "நிமிடங்களுக்கு முன்",
    alertsHoursAgo: "மணிக்கு முன்",
    alertsDaysAgo: "நாட்களுக்கு முன்",
  },

  te: {
    alertsLoadingMsg: "బహుళ-ప్రాంత వాతావరణ రాడార్లు మరియు IMD హెచ్చరిక బులెటిన్లు స్కాన్ అవుతున్నాయి...",
    alertsRedWarning: "ఎరుపు హెచ్చరికలు (వెంటనే చర్య తీసుకోండి)",
    alertsOrangeAlert: "నారింజ అప్రమత్తాలు (సిద్ధంగా ఉండండి)",
    alertsYellowWatch: "పసుపు పరిశీలన (అప్‌డేట్‌గా ఉండండి)",
    alertsImpactedStates: "ప్రభావిత రాష్ట్రాలు / కేంద్రపాలిత ప్రాంతాలు",
    alertsSeverityRed: "ఎరుపు హెచ్చరిక",
    alertsSeverityOrange: "నారింజ అప్రమత్తం",
    alertsSeverityYellow: "పసుపు పరిశీలన",
    alertsValidHorizon: "చెల్లుబాటు కాలం",
    alertsPublicAdvisory: "ప్రజా భద్రతా సలహా:",
    alertsViewAreaMap: "ప్రాంత మ్యాప్ చూడండి",
    alertsNoActiveTitle: "ఈ వర్గంలో సక్రియ అప్రమత్తాలు లేవు",
    alertsNoActiveDesc: "ఈ ఫిల్టర్ కోసం పర్యవేక్షించబడుతున్న అన్ని వాతావరణ కేంద్రాలు ప్రస్తుతం సాధారణ పరిమితుల్లో ఉన్నాయి.",
    alertsNoSubsTitle: "ఇంకా ఎటువంటి వ్యక్తిగత అర్లీ-వార్నింగ్ అప్రమత్తాలు సెట్ చేయబడలేదు.",
    alertsNoSubsDesc: "అధిక వర్షం, వడగాలులు లేదా తుఫాను గాలులకు అప్రమత్తాలు పొందడానికి దిగువన ఒక అప్రమత్తం సెట్ చేయండి!",
    alertsMonitoringActive: "పర్యవేక్షణ సక్రియం",
    alertsPaused: "నిలిపివేయబడింది",
    alertsTrigger: "ట్రిగ్గర్:",
    alertsThreshold: "పరిమితి:",
    alertsBrowserPush: "బ్రౌజర్ పుష్",
    alertsAudioSiren: "ఆడియో సైరన్",
    alertsNoGroundReportsTitle: "నమోదైన గ్రౌండ్ నివేదికలు కనుగొనబడలేదు",
    alertsNoGroundReportsDesc: "స్థానిక వాతావరణ సంఘటనలు, నీటి ముంపు లేదా గాలి నష్టం గురించి మొదట నివేదించండి!",
    alertsSubmitGroundReport: "గ్రౌండ్ నివేదిక సమర్పించండి",
    alertsCategoryHeavyRain: "భారీ వర్షం",
    alertsCategoryFlood: "అకస్మాత్ వరదలు",
    alertsCategoryCyclone: "తుఫాను",
    alertsCategoryHeatwave: "వడగాలులు",
    alertsCategoryFog: "దట్టమైన పొగమంచు",
    alertsCategoryDustStorm: "దుమ్ము తుఫాను",
    alertsCategoryStrongWinds: "తీవ్రమైన గాలులు",
    alertsCategoryHailstorm: "వడగండ్లు",
    alertsCategoryThunderstorm: "ఉరుముల తుఫాను",
    alertsCategoryOther: "తీవ్ర వాతావరణం",
    alertsStatusVerified: "ధృవీకరించబడింది",
    alertsStatusPending: "పెండింగ్‌లో",
    alertsStatusFlagged: "ఫ్లాగ్ చేయబడింది",
    alertsSoundEas: "EAS ద్విటోన్ సైరన్",
    alertsSoundSiren: "పురపాలక అలారం",
    alertsSoundPulse: "పల్స్ స్తకాటో",
    alertsSoundPing: "రాడార్ పింగ్",
    alertsSoundBell: "సలహా గంట",
    alertsHazardHeavyRain: "భారీ వర్షం / జోరువర్షం",
    alertsHazardHeatwave: "అత్యంత వడగాలులు",
    alertsHazardThunderstorm: "తీవ్ర తుఫాను / తీవ్ర గాలులు",
    alertsHazardColdWave: "తీవ్ర శీతలంఢెలు",
    alertsResumeMonitoring: "పర్యవేక్షణ తిరిగి ప్రారంభించండి",
    alertsPauseMonitoring: "పర్యవేక్షణ నిలిపివేయండి",
    alertsTestTone: "ఈ అప్రమత్తం టోన్ పరీక్షించండి",
    alertsDeleteAlert: "అప్రమత్తాన్ని తొలగించండి",
    alertsImpactLow: "IMD ప్రమాణం: మధ్యస్తం (5-15mm/h), భారీ (15-64mm/h), అత్యంత భారీ (>64mm/h)",
    alertsImpactHeatwave: "IMD ప్రమాణం: మైదానాల్లో 40°C-కు వడగాలి, 45°C+-కు తీవ్రమైన వడగాలి",
    alertsImpactThunderstorm: "స్క్వాల్ ప్రమాణం: మెరుపులతో 45-60 km/h కంటే అధిక గాలులు",
    alertsImpactColdWave: "శీతలంఢెలు ప్రమాణం: మైదానాల్లో కనిష్ఠ ఉష్ణోగ్రత 10°C లేదా అంతకంటే తక్కువ",
    alertsDetectingGps: "పరికర GPS గుర్తిస్తున్నాం...",
    alertsGpsCaptured: "GPS క్యాప్చర్ అయింది",
    socialFetchingStream: "లైవ్ ఇంటెలిజెన్స్ స్ట్రీమ్ తీసుకురాబడుతోంది...",
    socialFetchingDesc: "IMD అధికారిక, Google News, UN GDACS, X మరియు Instagram నుండి రియల్-టైమ్ అప్రమత్తాలు ఇంజెస్ట్ అవుతున్నాయి...",
    socialNoPostsTitle: "ఇంటెలిజెన్స్ పోస్టులు ఏవీ కనుగొనబడలేదు",
    socialNoPostsDesc: "ఎంచుకున్న ఫిల్టర్‌తో లైవ్ సిగ్నల్స్ ఏవీ సరిపోలడం లేదు.",
    socialIngestBtn: "ఇప్పుడే లైవ్ సిగ్నల్స్ ఇంజెస్ట్ చేయండి",
    socialShowAllBtn: "అన్ని ప్లాట్‌ఫారమ్‌లు చూపండి",
    socialCatHeavyRain: "భారీ వర్షం",
    socialCatFlood: "వరదలు",
    socialCatCyclone: "తుఫాను అప్రమత్తం",
    socialCatHeatwave: "వడగాలులు",
    socialCatHailstorm: "వడగండ్లు",
    socialCatThunderstorm: "ఉరుముల తుఫాను",
    socialCatOther: "వాతావరణ సంఘటన",
    socialPlatformImd: "IMD అధికారిక డెస్క్",
    socialPlatformGoogle: "Google News",
    socialPlatformTwitter: "X / Twitter",
    socialPlatformGdacs: "UN GDACS విపత్తు అప్రమత్తం",
    socialPlatformInstagram: "Instagram",
    socialOpenOnX: "X-లో తెరవండి",
    socialOpenImd: "IMD సలహా",
    socialOpenInstagram: "Instagram-లో తెరవండి",
    socialViewUnAlert: "UN అప్రమత్తం చూడండి",
    socialReadArticle: "వ్యాసం చదవండి",
    socialUrgency: "అత్యవసరత:",
    socialViewStation: "స్టేషన్ చూడండి",
    socialInferred: "అనుమానించబడింది:",
    socialNational: "జాతీయ",
    socialViewRadar: "రాడార్ చూడండి »",
    socialFetchingSignals: "సిగ్నల్స్ తీసుకురాబడుతున్నాయి...",
    socialFetchLive: "లైవ్ సిగ్నల్స్ తీసుకురండి",
    forecastToday: "ఈరోజు",
    forecastTodayHourly: "ఈరోజు (24 గంటలు) గంటవారీ వీక్షణ",
    forecastDayTable: "-రోజుల అంచనా పట్టిక",
    forecastTodayTitle: "ఈరోజు 24-గంటల గంటవారీ అంచనా",
    forecastDayTitle: "-రోజుల విస్తరించిన వాతావరణ అంచనా",
    forecastTimeInterval: "సమయ వ్యవధి (IST)",
    forecastDateDay: "తేదీ మరియు రోజు",
    forecastContextComprehensive: "(సమగ్ర)",
    forecastLiveTelemetry: "లైవ్ టెలిమెట్రీ • అప్‌డేట్ చేయబడింది",
    forecastIST: "IST",
    forecastRainChance: "% అవకాశం",
    forecastClearSky: "నిర్మలమైన ఆకాశం",
    forecastRainShowers: "వర్షపు జల్లులు",
    forecastClearNight: "నిర్మలమైన రాత్రి",
    forecastSunnyDay: "ఎండ రోజు",
    forecastPartlyCloudy: "పాక్షికంగా మేఘావృతం",
    forecastNoData: "అంచనా డేటా అందుబాటులో లేదు.",
    forecastUpdated: "అప్‌డేట్ చేయబడింది",
    forecastWindDir: "ESE (102°)",
    forecastDownloadSuccess: "-రోజుల వాతావరణ అంచనా CSV.",
    forecastDownloadError: "ఎగుమతికి అంచనా డేటా అందుబాటులో లేదు.",
    gpsCaptured: "GPS ద్వారా స్థానం గుర్తించబడింది!",
    gpsError: "GPS స్థానం పొందలేకపోయాము. దయచేసి నగరాన్ని మాన్యువల్‌గా నమోదు చేయండి.",
    locationIndia: "భారతదేశం",
    locationGpsCoords: "నా స్థానం",
    locationDetected: "గుర్తించబడిన స్థానం",
    locationCoordsFmt: "కస్టమ్ కోఆర్డినేట్",
    adminLoginBtn: "అడ్మిన్ లాగిన్",
    adminPortalBtn: "అడ్మిన్ పోర్టల్",
    alertsJustNow: "ఇప్పుడే",
    alertsMinsAgo: "నిమి క్రితం",
    alertsHoursAgo: "గంట క్రితం",
    alertsDaysAgo: "రోజుల క్రితం",
  }
};

// Merge new keys into master dict
Object.keys(newKeys).forEach(lang => {
  if (!master[lang]) master[lang] = {};
  Object.assign(master[lang], newKeys[lang]);
});

// Save back
fs.writeFileSync('scratch/master_comprehensive_dict.json', JSON.stringify(master, null, 2), 'utf8');
console.log(`Master dict updated. EN keys: ${Object.keys(master.en).length}`);
console.log('New keys added:', Object.keys(newKeys.en).length);
